spring:
  activemq:
    broker-url: tcp://11.0.0.123:61616
    user: admin
    password: admin
  mail:
    host: smtp.163.com
    username: 
    password: ''
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true

email_queue: sendemail
